/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CandidateProfileRouteImport } from './routes/candidate-profile'
import { Route as IndexRouteImport } from './routes/index'

const CandidateProfileRoute = CandidateProfileRouteImport.update({
  id: '/candidate-profile',
  path: '/candidate-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/candidate-profile': typeof CandidateProfileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/candidate-profile': typeof CandidateProfileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/candidate-profile': typeof CandidateProfileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/candidate-profile'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/candidate-profile'
  id: '__root__' | '/' | '/candidate-profile'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CandidateProfileRoute: typeof CandidateProfileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/candidate-profile': {
      id: '/candidate-profile'
      path: '/candidate-profile'
      fullPath: '/candidate-profile'
      preLoaderRoute: typeof CandidateProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CandidateProfileRoute: CandidateProfileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
